services:
  - type: web
    name: edubridge-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python migrate_db.py migrate
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: INTASEND_PUBLISHABLE_KEY
        sync: false
      - key: INTASEND_SECRET_KEY
        sync: false
      - key: INTASEND_API_URL
        value: https://api.intasend.com
